#! /bin/sh

bspc monitor -d main web file work ent chat misc term

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a firefox -d ^2
bspc rule -a mplayer2 --floating
bspc rule -a Kupfer.py --focus
bspc rule -a Screenkey --unmanage
bspc rule -a BSPWM_FRAME --frame

bspc config border_width        2
bspc config window_gap          5
bspc config split_ratio         0.52
bspc config top_padding 		0
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config normal_frame_opacity 0.0 
bspc config focused_frame_opacity 0.05
bspc config focused_border_color "#618485"
bspc config normal_border_color "#618485"
